services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: test
    ports:
      - 5432:5432
